### ISSUE TITLE
[BUG] report 2

### ISSUE THREAD

**Issue by Chichi244** [lego-build/lego-build#12]
### Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.

### What is the current behavior?

What does lego-build do?

### Steps to Reproduce

If the current behavior is a bug, if possible please provide the steps to reproduce.

### What is the expected behavior?

What should lego-build do ?

### Environment Details

Which versions of npm, and which browser and OS are affected by this issue?

**Comment by Onyelaudochukwuka** [comment]
We'll love to have more details on the error you're facing.
